<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gaml"
    nsURI="http://www.gama.msi/lang/gaml/Gaml" nsPrefix="gaml">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gaml" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//GamlLangDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlLangDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="k" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefKeyword"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefFacet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefBinaryOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefReserved"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="u" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefUnit"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefKeyword">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//GamlBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefFacet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefKeyword"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefFacet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefReserved"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefBinaryOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefReserved" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefReserved"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractGamlRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="GamlKeywordRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractGamlRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefKeyword"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlFacetRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractGamlRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefFacet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlBinarOpRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractGamlRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefBinaryOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlUnitRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractGamlRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlReservedRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractGamlRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//DefReserved"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//FacetExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubStatement" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//GamlKeywordRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetEval" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//SubStatement platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluation" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//SubStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FacetExpr" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//GamlFacetRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Row"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" upperBound="-1"
        eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//AbstractDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TerminalExpression" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignPlus" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignMin" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignMult" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignDiv" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ternary" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifTrue" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifFalse" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelNotEq" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelEq" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelEqEq" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelLtEq" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelGtEq" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelLt" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelGt" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pair" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multi" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pow" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlBinary" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//GamlBinarOpRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//GamlUnitRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamlUnary" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberRefP" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberRefR" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="func" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//VariableRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayRef" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//VariableRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="ecore:EClass platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntLiteral" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleLiteral" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorLiteral" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="platform:/resource/msi.gama.lang.gaml/src-gen/msi/gama/lang/gaml/Gaml.ecore#//TerminalExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
