/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractGamlJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(msi.gama.lang.gaml.gaml.GamlPackage.eINSTANCE);
		return result;
	}

}
