/**
 * generated by Xtext
 */
package msi.gama.lang.gaml.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Built In Equation Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see msi.gama.lang.gaml.gaml.GamlPackage#getBuiltInEquationDefinition()
 * @model
 * @generated
 */
public interface BuiltInEquationDefinition extends EquationDefinition
{
} // BuiltInEquationDefinition
