/**
 * generated by Xtext
 */
package msi.gama.lang.gaml.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see msi.gama.lang.gaml.gaml.GamlPackage#getUnary()
 * @model
 * @generated
 */
public interface Unary extends Expression
{
} // Unary
