<?xml version="1.0" encoding="UTF-8"?><!---->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:wiki="www.google.fr">

<xsl:template match="/">
 	<xsl:text>#summary Built-in Architectures (Developer Guide)
#sidebar G__TOC
=Built-in Architectures=
----
**This file is automatically generated from java files. Do Not Edit It.**

----


# INTRODUCTION

[Top of the page](#table-of-contents) 

----

## Table of Contents
&lt;wiki:toc max_depth="3" /&gt;
	</xsl:text>
	
<xsl:call-template name="buildSkillsByName"/>

<xsl:call-template name="buildSkills"/>

</xsl:template>

<xsl:template name="buildSkills">
	<xsl:for-each select="doc/architectures/architecture">
    	<xsl:sort select="@name" />

----
## <xsl:value-of select="@name"/>	
<xsl:value-of select="documentation/result"/> 
		<xsl:call-template name="buildVariables"/>
		<xsl:call-template name="buildActions"/>		
	</xsl:for-each>

</xsl:template>

    
 	<xsl:template name="buildVariables"> 
### Variables
	<xsl:for-each select="vars/var">		
	<xsl:sort select="@name" />   
* **`<xsl:value-of select="@name"/>`** (<xsl:value-of select="@type"/>): <xsl:value-of select="documentation/result"/> 
		</xsl:for-each>
	</xsl:template>

 	<xsl:template name="buildActions"> 
 	
### Actions 
	<xsl:for-each select="actions/action">		
	<xsl:sort select="@name" />  
	 
#### **`<xsl:value-of select="@name"/>`**
<xsl:value-of select="documentation/result"/>
* returns: <xsl:value-of select="@returnType"/>
  			<xsl:for-each select="args/arg"> 			
* **`<xsl:value-of select="@name"/>`** (<xsl:value-of select="@type"/>): <xsl:value-of select="documentation/result"/> 
  			</xsl:for-each>
		
<xsl:if test="documentation/examples[node()]">

```
<xsl:for-each select="documentation/examples/example" >
<xsl:if test="@code != ''"><xsl:value-of select="@code"/><xsl:text>
</xsl:text>
</xsl:if>
</xsl:for-each>```
</xsl:if>	
		
		</xsl:for-each>	

[Top of the page](#table-of-contents) 
	</xsl:template>
  
<xsl:template name="buildSkillsByName">
	<xsl:for-each select="doc/architectures/architecture"> 
		<xsl:sort select="@name" />
			<xsl:text>[</xsl:text> <xsl:value-of select="@name"/> <xsl:text>](#</xsl:text> <xsl:value-of select="@name"/> <xsl:text>), </xsl:text> 
	</xsl:for-each>   
</xsl:template> 
  
</xsl:stylesheet>
