/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GamlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return msi.gama.lang.gaml.ui.internal.GamlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return msi.gama.lang.gaml.ui.internal.GamlActivator.getInstance().getInjector("msi.gama.lang.gaml.Gaml");
	}
	
}
