#!/bin/bash
export GAMA_HEADLESS_HOME=../../../gama/ummisco.gama.product/target/products/ummisco.gama.application.product/linux/gtk/x86_64 #/headless
mpirun -np $2 java -cp $GAMA_HEADLESS_HOME/plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx4g -Djava.awt.headless=true org.eclipse.core.launcher.Main -application msi.gama.headless.id4 -MPI -v $1 logs