<?xml version="1.0" encoding="UTF-8"?><!---->
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:wiki="www.google.fr">
	<xsl:import href="docGaml-template-checkName-xml2wiki.xsl" />
	<xsl:import href="docGaml-template-generateExamples-xml2wiki.xsl" />

	<xsl:variable name="fileAK" select="'G__OperatorsAK'" />
	<xsl:variable name="fileLZ" select="'G__OperatorsLZ'" />
	<xsl:variable name="alphabetID" select="'*'" />
	<xsl:variable name="fileName" select="'Operators'" />
	<xsl:variable name="ak" select="'ak'" />
	<xsl:variable name="lz" select="'lz'" />


	<xsl:template match="/">
		<xsl:text>#summary Exhaustive list of GAMA Key words
#sidebar G__TOC
=</xsl:text>
		<xsl:value-of select="$fileName" />
		<xsl:text>=
----
&lt;font color="red"&gt; This file is automatically generated from java files. Do Not Edit It. &lt;/font&gt;
&lt;br/&gt;
----

	</xsl:text>
		&lt;br/&gt;
		----

		== Operators ==
		<xsl:for-each select="/doc/operators/operator">
			<xsl:sort select="@name" />
			<xsl:variable name="nameOp" select="@name" />
			<xsl:variable name="alphabetOrderOp" select="@alphabetOrder" />

			<xsl:for-each select="operatorCategories/category">
				<xsl:variable name="catItem" select="@id" />
				<xsl:text>[</xsl:text>
				<xsl:choose>
					<xsl:when test="$alphabetOrderOp = $ak">
						<xsl:value-of select="$fileAK" />
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$fileLZ" />
					</xsl:otherwise>
				</xsl:choose>
				<xsl:text>#</xsl:text>
				<xsl:value-of select="$nameOp" />
				<xsl:text> </xsl:text>
				<xsl:value-of select="$nameOp" />
				<xsl:text>],  </xsl:text>
			</xsl:for-each>
		</xsl:for-each>
		&lt;br/&gt;
		----

		== Statements ==
		<xsl:for-each select="/doc/statements/statement">
			<xsl:sort select="@name" />
			<xsl:text>[G__Statements#</xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text> </xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text>], </xsl:text>
		</xsl:for-each>
		&lt;br/&gt;
		----

		== Architectures ==

		<xsl:for-each select="/doc/architectures/architecture">
			<xsl:sort select="@name" />
			<xsl:text>[G__BuiltInControlArchitectures </xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text>], </xsl:text>

		</xsl:for-each>
		&lt;br/&gt;
		----

		== Constants and colors ==

		<xsl:for-each select="/doc/constants/constant">
			<xsl:sort select="@name" />

			<xsl:text>[G__UnitsAndConstants </xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text>]</xsl:text>
			<xsl:if test="@altNames">
				<xsl:text> (</xsl:text>
				<xsl:value-of select="@altNames" />
				<xsl:text>)</xsl:text>
			</xsl:if>
			<xsl:text>, </xsl:text>
		</xsl:for-each>



		&lt;br/&gt;
		----
		== Skills ==
		<xsl:for-each select="/doc/skills/skill">
			<xsl:sort select="@name" />
			<xsl:text>[G__BuiltInSkills#</xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text> </xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text>], </xsl:text>
		</xsl:for-each>

		&lt;br/&gt;
		----
		== Species ==

		<xsl:for-each select="/doc/speciess/species">
			<xsl:sort select="@name" />
			<xsl:text>[G__BuiltInSpecies#</xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text> </xsl:text>
			<xsl:value-of select="@name" />
			<xsl:text>], </xsl:text>
		</xsl:for-each>
		[G__BuiltInSpecies#model world]

		&lt;br/&gt;
		----

		== Actions ==
		<xsl:for-each select="/doc/speciess/species">
			<xsl:sort select="@name" />
			<xsl:for-each select="actions/action">
				<xsl:text>[G__BuiltInSpecies#</xsl:text>
				<xsl:value-of select="@name" />
				<xsl:text> </xsl:text>
				<xsl:value-of select="@name" />
				<xsl:text>], </xsl:text>
			</xsl:for-each>
		</xsl:for-each>

		<xsl:for-each select="/doc/skills/skill">
			<xsl:sort select="@name" />
			<xsl:for-each select="actions/action">
				<xsl:text>[G__BuiltInSkills#</xsl:text>
				<xsl:value-of select="@name" />
				<xsl:text> </xsl:text>
				<xsl:value-of select="@name" />
				<xsl:text>], </xsl:text>
			</xsl:for-each>
		</xsl:for-each>
		&lt;br/&gt;
		----

		== Variables ==
		<xsl:for-each select="/doc/skills/skill">
			<xsl:sort select="@name" />
			<xsl:for-each select="vars/var">
				<xsl:text>[G__BuiltInSkills </xsl:text>
				<xsl:value-of select="@name" />
				<xsl:text>], </xsl:text>
			</xsl:for-each>
		</xsl:for-each>
		&lt;br/&gt;
		----

		== Pseudo-Variables ==

		[G__PseudoVariables#self self], [G__PseudoVariables#myself myself], [G__PseudoVariables#each
		each]
		&lt;br/&gt;
		----


		== Types ==
		[G__DataTypes#bool bool], [G__DataTypes#float float], [G__DataTypes#int int],
		[G__DataTypes#string string], [G__DataTypes#agent agent],
		[G__DataTypes#container container]
		, [G__DataTypes#file file], [G__DataTypes#geometry geometry],
		[G__DataTypes#graph graph], [G__DataTypes#list list],
		[G__DataTypes#map map], [G__DataTypes#matrix matrix]
		, [G__DataTypes#pair pair], [G__DataTypes#path path],
		[G__DataTypes#point point], [G__DataTypes#rgb rgb], [G__DataTypes#rgb
		color], [G__DataTypes#species species], [G__DataTypes#topology
		topology]
		&lt;br/&gt;
		----

		== [G__GlobalSpecies the world] ==
		[G__GlobalSpecies torus], [G__GlobalSpecies#Environment_Size Environment Size],
		[G__GlobalSpecies#world world], [G__GlobalSpecies#time time]
		[G__GlobalSpecies#cycle cycle], [G__GlobalSpecies#step step],
		[G__GlobalSpecies#time time], [G__GlobalSpecies#duration duration],
		[G__GlobalSpecies#total_duration total_duration]
		[G__GlobalSpecies#average_duration average_duration],
		[G__GlobalSpecies#machine_time machine_time], [G__GlobalSpecies#agents
		agents], [G__GlobalSpecies#halt stop], [G__GlobalSpecies#halt halt],
		[G__GlobalSpecies#pause pause], [G__GlobalSpecies#scheduling
		scheduling]

		&lt;br/&gt;
		----

		== Grid ==
		[G__GridSpecies#grid_x grid_x], [G__GridSpecies#grid_y grid_y], [G__GridSpecies#agents
		agents], [G__GridSpecies#color color], [G__GridSpecies#grid_value
		grid_value]

		&lt;br/&gt;
		----

		== Other concepts ==

		[G__RuntimeConcepts#Scheduling_of_Agents scheduling], [G__RuntimeConcepts#Agents_Step step], [G__KeyConcepts
		Key concepts],
		[G__KeyConcepts#Vocabulary_correspondance_with_the_agent-based_paradigm_as_in_Ne
		correspondance GAMA Netlogo],
		[G__KeyConcepts#Translation_into_a_concrete_syntax operators
		statements type species]

	</xsl:template>


</xsl:stylesheet>
