/**
* Name: $TITLE$
* $DESC$ 
* Author: $AUTHOR$
* Tags: 
*/

model $TITLE$

global {
	/** Insert the global definitions, variables and actions here */
	setup {
		/** Insert any initialization to run before each of the tests */
	}
	
	test "My First Test" {
	/** Insert here any assertion you need to test */
	}
	
}

experiment $TITLE$ type: test autorun: true {
	/** Alternatively or in addition, you can insert here tests definitions */

}
