#!/bin/bash

chmod a+rw -R /opt/gama-platform
chmod a+x -R /opt/gama-platform/Gama
chmod a+x -R /opt/gama-platform/headless/gama-headless.sh

# Add gama-headless.sh shortcut in PATH
ln -s /opt/gama-platform/headless/gama-headless.sh /usr/sbin/gama-headless