/**
 * generated by Xtext
 */
package msi.gama.lang.gaml.gaml.impl;

import msi.gama.lang.gaml.gaml.BuiltInActionDefinition;
import msi.gama.lang.gaml.gaml.GamlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Built In Action Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BuiltInActionDefinitionImpl extends ActionDefinitionImpl implements BuiltInActionDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BuiltInActionDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.BUILT_IN_ACTION_DEFINITION;
  }

} //BuiltInActionDefinitionImpl
