#!/bin/bash
export GAMA_HEADLESS_HOME=/mnt/c/Users/lucas/Documents/GitHub/gama_true/gama/ummisco.gama.product/target/products/ummisco.gama.application.product/linux/gtk/x86_64 #/headless
mpirun -np $2 -output-filename output.log java -cp $GAMA_HEADLESS_HOME/plugins/org.eclipse.equinox.launcher*.jar -Xms512m -Xmx4g -Djava.awt.headless=true org.eclipse.core.launcher.Main -configuration $GAMA_HEADLESS_HOME/headless/configuration -application msi.gama.headless.product -data $GAMA_HEADLESS_HOME/headless/ws -v $1 output.log
