/*
 * generated by Xtext
 */
package msi.gama.lang.gaml.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class GamlValidator extends AbstractGamlValidator {
	
//	public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					GamlPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
