/*********************************************************************************************
 * 
 *
 * 'CommitEventHandler.java', in plugin 'msi.gama.application', is part of the source code of the 
 * GAMA modeling and simulation platform.
 * (c) 2007-2014 UMI 209 UMMISCO IRD/UPMC & Partners
 * 
 * Visit https://code.google.com/p/gama-platform/ for license information and developers contact.
 * 
 * 
 **********************************************************************************************/
package msi.gama.gui.svn;

import org.tmatesoft.svn.core.*;
import org.tmatesoft.svn.core.wc.*;

/**
 * This class is an implementation of ISVNEventHandler intended for processing
 * events generated by do*() methods of an SVNCommitClient object. An instance
 * of this handler will be provided to an SVNCommitClient. When calling, for
 * example, SVNCommitClient.doCommit(..) on a WC path, this method will generate
 * an event for each 'adding'/'deleting'/'sending'/.. action it will perform
 * upon every path being committed. And this event is passed to
 * 
 * ISVNEventHandler.handleEvent(SVNEvent event, double progress)
 * 
 * to notify the handler. The event contains detailed information about the
 * path, action performed upon the path and some other.
 */
public class CommitEventHandler implements ISVNEventHandler {

	/**
	 * progress is currently reserved for future purposes and now is always
	 * ISVNEventHandler.UNKNOWN
	 */
	@Override
	public void handleEvent(final SVNEvent event, final double progress) {
		/*
		 * Gets the current action. An action is represented by SVNEventAction.
		 * In case of a commit an action can be determined via comparing
		 * SVNEvent.getAction() with SVNEventAction.COMMIT_-like constants.
		 */
		SVNEventAction action = event.getAction();
		if ( action == SVNEventAction.COMMIT_MODIFIED ) {
			System.out.println("Sending   " + event.getURL());
		} else if ( action == SVNEventAction.COMMIT_DELETED ) {
			System.out.println("Deleting   " + event.getURL());
		} else if ( action == SVNEventAction.COMMIT_REPLACED ) {
			System.out.println("Replacing   " + event.getURL());
		} else if ( action == SVNEventAction.COMMIT_DELTA_SENT ) {
			System.out.println("Transmitting file data....");
		} else if ( action == SVNEventAction.COMMIT_ADDED ) {
			/*
			 * Gets the MIME-type of the item.
			 */
			String mimeType = event.getMimeType();
			if ( SVNProperty.isBinaryMimeType(mimeType) ) {
				/*
				 * If the item is a binary file
				 */
				System.out.println("Adding  (bin)  " + event.getURL());
			} else {
				System.out.println("Adding         " + event.getURL());
			}
		}

	}

	/**
	 * Should be implemented to check if the current operation is cancelled. If
	 * it is, this method should throw an SVNCancelException.
	 */
	@Override
	public void checkCancelled() throws SVNCancelException {}

}